In [1]:
import pandas as pd
import numpy as np 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
#load data
data = pd.read_csv('HT4.csv')
tweets= data.tweet
tweets.head()

0                 وصارت فطاير البقالات غذاء صحي 👎🏻 URL
1    @USER روحي لبريده تلقين اشباه كثير بس ماحد زيك...
2           @USER مش باين حاجه خالص 😣<LF>مش عارف بقى 😔
3    #اليوم_الاثنين<LF><LF>👏 يقولك :%90  من المسلمي...
4                     حمدلله ماحطها في فمي اساسا😷🤢 URL
Name: tweet, dtype: object

In [11]:
labels= data.OFF

In [13]:
#split train & test data
from sklearn.model_selection import train_test_split
xtr,xts,ytr,yts= train_test_split(tweets,labels,test_size=0.2)
len(xtr),len(ytr)

(6844, 6844)

In [17]:
#tf idf
tf_idf = TfidfVectorizer()
#applying tf idf to training data
X_train_tf = tf_idf.fit_transform(xtr)
X_train_tf = tf_idf.transform(xtr)

In [18]:
print("n_samples: %d, n_features: %d" % X_train_tf.shape)

n_samples: 6844, n_features: 27914


In [19]:
#transforming test data into tf-idf matrix
X_test_tf = tf_idf.transform(xts)
print("n_samples: %d, n_features: %d" % X_test_tf.shape)

n_samples: 1711, n_features: 27914


In [22]:
#naive bayes
from sklearn.naive_bayes import MultinomialNB
naive_bayes_classifier = MultinomialNB()
naive_bayes_classifier.fit(X_train_tf, ytr)

MultinomialNB()

In [24]:
from sklearn import metrics
#predicted y
y_pred = naive_bayes_classifier.predict(X_test_tf)
print(metrics.classification_report(yts, y_pred, target_names=['Positive', 'Negative']))

              precision    recall  f1-score   support

    Positive       0.69      0.98      0.81      1096
    Negative       0.83      0.20      0.32       615

    accuracy                           0.70      1711
   macro avg       0.76      0.59      0.56      1711
weighted avg       0.74      0.70      0.63      1711



In [26]:
print("Confusion matrix:")
print(metrics.confusion_matrix(yts, y_pred))

Confusion matrix:
[[1070   26]
 [ 491  124]]


In [31]:
#random forest
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(n_estimators=50)
random_forest.fit(X_train_tf,ytr)

RandomForestClassifier(n_estimators=50)

In [32]:
#predicted y
y_pred = random_forest.predict(X_test_tf)
print(metrics.classification_report(yts, y_pred, target_names=['Positive', 'Negative']))

              precision    recall  f1-score   support

    Positive       0.69      0.96      0.80      1096
    Negative       0.77      0.24      0.36       615

    accuracy                           0.70      1711
   macro avg       0.73      0.60      0.58      1711
weighted avg       0.72      0.70      0.65      1711



In [33]:
print("Confusion matrix:")
print(metrics.confusion_matrix(yts, y_pred))

Confusion matrix:
[[1051   45]
 [ 468  147]]


In [34]:
#svm
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train_tf,ytr)

SVC()

In [37]:
#predicted y
y_pred = svm.predict(X_test_tf)
print(metrics.classification_report(yts, y_pred, target_names=['Positive', 'Negative']))

              precision    recall  f1-score   support

    Positive       0.71      0.93      0.81      1096
    Negative       0.73      0.33      0.46       615

    accuracy                           0.72      1711
   macro avg       0.72      0.63      0.63      1711
weighted avg       0.72      0.72      0.68      1711



In [36]:
print("Confusion matrix:")
print(metrics.confusion_matrix(yts, y_pred))

Confusion matrix:
[[1051   45]
 [ 468  147]]
